# Generated by Django 4.2.20 on 2025-04-14 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='allowed_radius',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='classsession',
            name='longitude',
        ),
    ]
