# Generated by Django 4.2.20 on 2025-04-14 20:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_classsession_allowed_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='semester',
            field=models.CharField(choices=[('Jan-Apr', 'January - April'), ('May-Aug', 'May - August'), ('Sep-Dec', 'September - December')], default='Jan-Apr', max_length=7),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturers',
            field=models.ManyToManyField(related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
