# Generated by Django 4.2.20 on 2025-04-14 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_number',
            new_name='admission_number',
        ),
    ]
