# Generated by Django 4.2.20 on 2025-04-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_rename_roll_number_student_admission_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='distance_from_class',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='longitude',
        ),
    ]
