# Generated by Django 4.2.20 on 2025-04-14 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_remove_attendancerecord_distance_from_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='flag_reason',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='flagged',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='ip_address',
        ),
    ]
