# Generated by Django 4.2.20 on 2025-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_attendancerecord_flag_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
